# Generated by Django 4.2.30 on 2026-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysisresult_ai_suggestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='improvement_notes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='rewritten_resume',
            field=models.TextField(blank=True, default=''),
        ),
    ]
