# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analysisresult_improvement_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='company_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='difficulty',
            field=models.CharField(default='Intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
