# Generated by Django 4.2.30 on 2026-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aifeedback_industrytrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='active_ai_model',
            field=models.CharField(default='Gemini', max_length=100),
        ),
    ]
