# Generated by Django 4.2.30 on 2026-05-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_analysisresult_active_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
