# Generated by Django 4.2.30 on 2026-05-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resume_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='interview_questions',
            field=models.JSONField(default=list),
        ),
    ]
