# Generated by Django 4.2.30 on 2026-05-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_analysisresult_interview_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='target_industry',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
