# Generated by Django 4.2.30 on 2026-05-17 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resume_target_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved & Deployed'), ('rejected', 'Rejected & Discarded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('analysis_log', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(max_length=255, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_pics/'),
        ),
    ]
