# Generated by Django 4.2.30 on 2026-05-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pendingdeployment_alter_resume_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='structured_data',
            field=models.JSONField(default=dict),
        ),
    ]
